### ISSUE TITLE
 出错了

### ISSUE THREAD

**Issue by AndySze** [louisun/iSearch#7]
```bash
Traceback (most recent call last):
  File "/usr/local/bin/s", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/iSearch/isearch.py", line 569, in main
    search_database(word)
  File "/usr/local/lib/python2.7/site-packages/iSearch/isearch.py", line 234, in search_database
    print(colored(word + ' 不在数据库中，从有道词典查询', 'white', 'on_red'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-28: ordinal not in range(128)
```
环境是macOS

**Comment by louisun** [comment]
是否是最新的版本？pip install -U isearch 更新下，Python2 应该没问题啊

**Comment by AndySze** [comment]
```bash
pip install -U isearch
Collecting isearch
  Downloading https://files.pythonhosted.org/packages/ba/40/79d3b01e6b5ed88addcece66adc728d581a2987a1228b8d52aa72b14660a/iSearch-1.0.2-py2.py3-none-any.whl
Requirement not upgraded as not directly required: requests in /usr/local/lib/python2.7/site-packages (from isearch) (0.14.2)
Requirement not upgraded as not directly required: bs4 in /usr/local/lib/python2.7/site-packages (from isearch) (0.0.1)
Requirement not upgraded as not directly required: termcolor in /usr/local/lib/python2.7/site-packages (from isearch) (1.1.0)
Requirement not upgraded as not directly required: beautifulsoup4 in /usr/local/lib/python2.7/site-packages (from bs4->isearch) (4.1.3)
stevedore 0.8 requires distribute, which is not installed.
pyinstaller 2.1 requires distribute, which is not installed.
aeneas 1.7.3.0 has requirement BeautifulSoup4>=4.5.1, but you'll have beautifulsoup4 4.1.3 which is incompatible.
fabric 1.6.1 has requirement paramiko>=1.10.0, but you'll have paramiko 1.9.0 which is incompatible.
protobuf 3.5.1 has requirement six>=1.9, but you'll have six 1.3.0 which is incompatible.
Installing collected packages: isearch
Successfully installed isearch-1.0.2
```
好像有几个问题，但升级成功了。

但问题依旧还在，不知道什么原因。Python3也试过，同样的问题。

**Comment by louisun** [comment]
我没法重现你这个问题，建议你用 pyenv 装一下 Python 环境

**Comment by xain** [comment]
我在ubuntu 16.04上也遇到这个问题。
