### ISSUE TITLE
module 'html5lib.treebuilders' has no attribute '_base'

### ISSUE THREAD

**Issue by NamelessAshone** [louisun/iSearch#8]
你好，朋友
由于一些不知名的原因，iSearch最近无法使用了。
错误信息如下：
λ ~/Tools/ s heap
Traceback (most recent call last):
  File "/usr/local/bin/s", line 7, in <module>
    from iSearch.isearch import main
  File "/usr/local/lib/python3.5/dist-packages/iSearch/isearch.py", line 9, in <module>
    import bs4
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

我尝试过使用`sudo pip3 install -U iSearch`对程序进行更新，但依然会出现上述错误。

**Comment by NamelessAshone** [comment]
感谢StackOverflow
原因是上游的包html5lib、beautifulsoup4的版本问题
使用下述命令即可解决：
`sudo pip3 install --upgrade beautifulsoup4 html5lib`
